repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/nix-community/nixpkgs-fmt
  rev: v1.3.0
  hooks:
    - id: nixpkgs-fmt

- repo: local
  hooks:
    - id: flake-check
      name: Check Nix flake
      entry: nix flake check
      language: system
      pass_filenames: false
      files: 'flake\.nix$'